import { test } from "node:test";
import assert from "node:assert/strict";
import * as R from "./src/raid.mjs";
import * as I from "./src/ai.mjs";

const C = R.SAMPLE_CHAMPIONS;
const throwsType = (fn, prefix = "invalid argument") => assert.throws(fn, (e) => e instanceof TypeError && e.message.startsWith(prefix), `expected TypeError "${prefix}..."`);
const near = (a, b, tol = 1e-12) => assert.ok(typeof a === "number" && Math.abs(a - b) <= tol, `|${a} - ${b}| > ${tol}`);
const mk = (id, level = 1) => R.makeChampion(C[id], level);
const unit = (id, extra = {}) => ({ ...mk(id), effects: [], ...extra });
const en = (list) => list.map(([id, hp]) => ({ ...mk(id), hp, effects: [] }));
const teams = () => ({ A: [mk("kael"), mk("vell")], B: [mk("grim"), mk("nyx")] });

test("stage 1: chooseTargetSmart", () => {
	const k = unit("kael");
	assert.equal(I.chooseTargetSmart(k, en([["grim", 1800], ["nyx", 1400]])), 0);
	assert.equal(I.chooseTargetSmart(k, en([["nyx", 100], ["grim", 1800]])), 1);
	assert.equal(I.chooseTargetSmart(k, en([["grim", 0], ["nyx", 1400]])), 1);
	assert.equal(I.chooseTargetSmart(k, en([["vell", 500], ["nyx", 400]])), 1);
	assert.equal(I.chooseTargetSmart(k, en([["grim", 900], ["grim", 800]])), 1);
	assert.equal(I.chooseTargetSmart(k, en([["grim", 900], ["grim", 900]])), 0);
	assert.equal(I.chooseTargetSmart(k, []), -1);
	assert.equal(I.chooseTargetSmart(k, en([["nyx", 0]])), -1);
	assert.equal(I.chooseTargetSmart(unit("vell"), en([["kael", 100], ["grim", 50], ["nyx", 10]])), 0);
	throwsType(() => I.chooseTargetSmart({ stats: {} }, []));
	throwsType(() => I.chooseTargetSmart(k, "x"));
	throwsType(() => I.chooseTargetSmart(k, [{ affinity: "magic" }]));
});
test("stage 1: scoreSkills", () => {
	const k = unit("kael");
	const s2 = I.scoreSkills(k, 2);
	assert.deepEqual(s2.map((x) => x.skill), [0, 1, 2]);
	near(s2[0].score, 1);
	near(s2[1].score, 1.4);
	near(s2[2].score, 1.8);
	near(I.scoreSkills(k, 1)[1].score, 0.7);
	const cd = I.scoreSkills({ ...k, cooldowns: { 2: 3 } }, 3);
	assert.deepEqual(cd.map((x) => x.skill), [0, 1]);
	near(cd[1].score, 2.0999999999999996);
	assert.deepEqual(I.scoreSkills(unit("nyx"), 2), [{ skill: 0, score: 1 }, { skill: 1, score: 1.5 }, { skill: 2, score: 2.2 }]);
	assert.deepEqual(I.scoreSkills(unit("vell"), 2), [{ skill: 0, score: 1 }, { skill: 1, score: 1.5 }]);
	assert.deepEqual(I.scoreSkills(unit("vell", { effects: [{ stat: "atk", pct: 25, turns: 1 }] }), 2), [{ skill: 0, score: 1 }, { skill: 1, score: -1 }]);
	assert.deepEqual(I.scoreSkills(unit("vell", { effects: [{ stat: "def", pct: 25, turns: 1 }] }), 2), [{ skill: 0, score: 1 }, { skill: 1, score: 1.5 }]);
	throwsType(() => I.scoreSkills(k, -1));
	throwsType(() => I.scoreSkills(k, 1.5));
	throwsType(() => I.scoreSkills({}, 1));
});
test("stage 1: chooseSkillSmart", () => {
	const k = unit("kael");
	assert.equal(I.chooseSkillSmart(k, 2), 2);
	assert.equal(I.chooseSkillSmart(k, 1), 2);
	assert.equal(I.chooseSkillSmart({ ...k, cooldowns: { 2: 3 } }, 3), 1);
	assert.equal(I.chooseSkillSmart({ ...k, cooldowns: { 2: 1 } }, 1), 0);
	assert.equal(I.chooseSkillSmart({ ...k, cooldowns: { 2: 1 } }, 2), 1);
	const n = unit("nyx");
	assert.equal(I.chooseSkillSmart(n, 2), 2);
	assert.equal(I.chooseSkillSmart({ ...n, cooldowns: { 2: 2 } }, 2), 1);
	assert.equal(I.chooseSkillSmart({ ...n, cooldowns: { 2: 2 }, effects: [{ stat: "spd", pct: 30, turns: 1 }] }, 2), 0);
	assert.equal(I.chooseSkillSmart(unit("vell"), 2), 1);
	assert.equal(I.chooseSkillSmart(unit("vell", { effects: [{ stat: "atk", pct: 25, turns: 1 }] }), 2), 0);
	const tie = { ...k, skills: [{ ...k.skills[0] }, { ...k.skills[0], name: "Twin", cooldown: 2 }] };
	assert.equal(I.chooseSkillSmart(tie, 1), 1);
	throwsType(() => I.chooseSkillSmart(k, -1));
});
test("stage 2: runBattleSmart seed 1", () => {
	const { A, B } = teams();
	const b = I.runBattleSmart(A, B, 1);
	assert.deepEqual(Object.keys(b).sort(), ["log", "turns", "units", "winner"]);
	assert.equal(b.winner, "A");
	assert.equal(b.turns, 37);
	assert.deepEqual(b.units.map((u) => u.hp), [321, 0, 0, 0]);
	assert.deepEqual(b.log[0], { turn: 1, actor: 3, skill: 2, hits: [{ target: 1, damage: 294, crit: false, killed: false }] });
	assert.deepEqual(b.log[1], { turn: 2, actor: 0, skill: 2, hits: [{ target: 2, damage: 425, crit: true, killed: false }] });
	assert.deepEqual(b.log.slice(2, 5).map((t) => [t.actor, t.skill, t.hits.length]), [[1, 1, 0], [2, 1, 0], [3, 1, 0]]);
	assert.deepEqual(b.log[5].hits.map((h) => [h.target, h.damage, h.crit]), [[2, 127, false], [3, 104, false]]);
	assert.deepEqual(b.log[6], { turn: 7, actor: 1, skill: 0, hits: [{ target: 2, damage: 85, crit: false, killed: false }] });
	assert.deepEqual(b.log[36], { turn: 37, actor: 0, skill: 2, hits: [{ target: 3, damage: 345, crit: true, killed: true }] });
	assert.equal(A[0].hp, 1500, "input untouched");
	assert.equal(A[0].tm, undefined);
	const basic = R.runBattle(A, B, 1);
	assert.deepEqual([basic.winner, basic.turns, basic.units[0].hp], ["A", 35, 1103]);
});
test("stage 2: runBattleSmart three turns and validation", () => {
	const { A, B } = teams();
	const b = I.runBattleSmart(A, B, 1, 3);
	assert.equal(b.winner, "draw");
	assert.equal(b.turns, 3);
	assert.deepEqual(b.units.map((u) => u.hp), [1500, 956, 1375, 1400]);
	assert.deepEqual(b.units.map((u) => u.cooldowns), [{ 2: 4 }, { 1: 3 }, {}, { 2: 5 }]);
	assert.deepEqual(b.units.map((u) => u.effects), [[{ stat: "atk", pct: 25, turns: 2 }], [{ stat: "atk", pct: 25, turns: 1 }], [{ stat: "def", pct: -30, turns: 2 }], []]);
	assert.deepEqual(b.units.map((u) => u.side), [0, 0, 1, 1]);
	assert.deepEqual(I.runBattleSmart(A, B, 4), I.runBattleSmart(A, B, 4));
	throwsType(() => I.runBattleSmart([], B, 1));
	throwsType(() => I.runBattleSmart(A, [], 1));
	throwsType(() => I.runBattleSmart(A, B, 1.5));
	throwsType(() => I.runBattleSmart(A, B, 1, 0));
});
test("stage 3: winRate", () => {
	const { A, B } = teams();
	const seeds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
	assert.deepEqual(I.winRate(A, B, seeds), { wins: 3, draws: 0, total: 10, rate: 0.3, avgTurns: 37.2 });
	assert.deepEqual(I.winRate(A, B, seeds, R.runBattle), { wins: 10, draws: 0, total: 10, rate: 1, avgTurns: 37.5 });
	assert.deepEqual(I.winRate([mk("kael")], [mk("grim")], [1, 2, 3, 4, 5]), { wins: 5, draws: 0, total: 5, rate: 1, avgTurns: 16.4 });
	assert.deepEqual(I.winRate([mk("kael")], [mk("grim")], [1, 2, 3, 4, 5], R.runBattle).avgTurns, 17.6);
	assert.deepEqual(I.winRate([mk("vell")], R.stageEnemies(9), [3, 4]), { wins: 0, draws: 0, total: 2, rate: 0, avgTurns: 15.5 });
	assert.deepEqual(I.winRate(A, R.stageEnemies(2), seeds).avgTurns, 16.4);
	assert.deepEqual(I.winRate(A, R.stageEnemies(2), seeds, R.runBattle).avgTurns, 17.6);
	let calls = [];
	const fake = (a, b, s) => (calls.push(s), { winner: s % 3 === 0 ? "draw" : s % 2 ? "A" : "B", turns: s });
	assert.deepEqual(I.winRate(A, B, [1, 2, 3, 4], fake), { wins: 1, draws: 1, total: 4, rate: 0.25, avgTurns: 2.5 });
	assert.deepEqual(calls, [1, 2, 3, 4]);
	throwsType(() => I.winRate(A, B, []));
	throwsType(() => I.winRate(A, B, [1.5]));
	throwsType(() => I.winRate(A, B, "1"));
	throwsType(() => I.winRate(A, B, [1], 5));
});
